name: Go-Ubiq GitHub Actions Release Builder

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out ubiq/go-ubiq
      uses: actions/checkout@v2
      with:
        repository: ubiq/go-ubiq
        ref: v5.2.0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Build
      run: make gubiq
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build/bin/gubiq
        path: gubiq-linux-amd64

