name: Go-Ubiq GitHub Actions Release Builder

on:
  push:

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out ubiq/go-ubiq
      uses: actions/checkout@v2
      with:
        repository: ubiq/go-ubiq
        ref: v5.2.0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Build
      run: |
        go run build/ci.go install ./cmd/gubiq
        mv build/bin/gubiq build/bin/gubiq-linux-amd64
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gubiq-linux-amd64
        path: build/bin/gubiq-linux-amd64

  build-mac:
    runs-on: macos-11
    steps:
    - name: Check out ubiq/go-ubiq
      uses: actions/checkout@v2
      with:
        repository: ubiq/go-ubiq
        ref: v5.2.0
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Build
      run: |
        go run build/ci.go install ./cmd/gubiq
        mv build/bin/gubiq build/bin/gubiq-darwin-amd64
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gubiq-darwin-amd64
        path: build/bin/gubiq-darwin-amd64
